</div>

<div id="footer">
<?php if ($_REQUEST["nosidebar"] != "y") { ?>

	<div style="clear:both;display:block;width:600px;padding-top:35px;margin-left:240px">
		<div class="a15">CESTA | Spatial History Project</div>
		<div class="a12" style="color:#808080;padding-top:5px;line-height:18px;letter-spacing:.02em;">Wallenberg Hall, 450 Serra Mall<br />
		Mail: Bldg 160, Rm 228 - In Person: Fourth Floor<br />
		Stanford, CA 94305-2055<br />
		<hr style="color:#666;width:775px;height:1px;" />
		<img src="/media/images/3bullets.png" alt="Copyright Spatial History Project" style="margin-bottom:4px;margin-top:2px;" />
		<br />
		</div>
		<div class="a12" style="color:#666;line-height:20px;margin-bottom:5px">&copy;<?=date("Y")?>&nbsp;&nbsp;&nbsp;The Spatial History Project&nbsp;&nbsp;&nbsp;All Rights Reserved<br /></div>
		<div style="color:#666;font-family:'Source Sans Pro', sans-serif;font-size:12px;line-height:14px;width:790px;">
		The Spatial History Project at Stanford University, a part of the Center for Spatial and Textual Analysis, is made possible by the generous funding of the Vice Provost for Undergraduate Education (VPUE), DoResearch, The Andrew W. Mellon Foundation, and The Wallenberg Foundation Media Places Initiative.<br />
		</div>
		<div style="color:#666;font-family:'Source Sans Pro', sans-serif;;font-size:12px;line-height:14px;padding-bottom:34px;">v3<br /></div>

	</div>
</div>
<?php } else { ?>

<div style="clear:both;display:block;width:600px;padding-top:35px;margin-left:26px">
		<div class="a15">CESTA | Spatial History Project</div>
		<div class="a12" style="color:#808080;padding-top:5px;line-height:18px;letter-spacing:.02em;">Wallenberg Hall, 450 Serra Mall<br />
		Bldg 160, Rm 228<br />
		Stanford, CA 94305-2055<br />
		<hr style="color:#666;width:775px;height:1px;" />
		<img src="/media/images/3bullets.png" alt="Copyright Spatial History Project" style="margin-bottom:4px;margin-top:2px;" />
		<br />
		</div>
		<div class="a12" style="color:#666;line-height:20px;margin-bottom:5px">&copy;<?=date("Y")?>&nbsp;&nbsp;&nbsp;The Spatial History Project&nbsp;&nbsp;&nbsp;All Rights Reserved<br /></div>
		<div style="color:#666;font-family:'Source Sans Pro', sans-serif;font-size:12px;line-height:14px;width:790px;">
		The Spatial History Project at Stanford University, a part of the Center for Spatial and Textual Analysis, is made possible by the generous funding of the Vice Provost for Undergraduate Education (VPUE), DoResearch, The Andrew W. Mellon Foundation, and The Wallenberg Foundation Media Places Initiative.<br />
		<br><br></div>


	</div>
</div>
<?php }  if (!$nofootgraphic) { ?>
<div><img src="/media/images/bottom_corner.png" alt="Spatial History" style="position:fixed;z-index:-1;bottom:0;right:0;" /></div>
<?php } ?>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-1066211-4");
pageTracker._trackPageview();
} catch(err) {}




	


</script>





</body>
</html>